# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under text2sql_rag_app/resources/*
# and text2sql_rag_app/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for text2sql_rag_app Staging

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./text2sql_rag_app

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: text2sql_rag_app-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.212.2
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t asong_dev
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t asong_dev
